org.gradle.jvmargs=-Xmx2G
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=true

# https://projects.neoforged.net/neoforged/neoforge
neoforgeVersion=21.1.90
neoForge.parchment.minecraftVersion=1.21.1
neoForge.parchment.mappingsVersion=2024.11.17

minecraftVersion=1.21.1
modId=endermanoverhaul
version=2.0.2
group=tech.alexnijjar.endermanoverhaul

resourcefulLibVersion=3.0.11
resourcefulConfigVersion=3.0.7
geckolibVersion=4.7
mekanismVersion=10.7.8.70

